# Generated by Django 4.0.3 on 2022-04-13 14:27

import django.core.validators
from django.db import migrations, models
import sports_app.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[sports_app.common.validators.validate_only_letters, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[sports_app.common.validators.validate_only_letters, django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='sportsappuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[sports_app.common.validators.validate_letters_numbers_and_dashes_only, django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
