# Generated by Django 4.0.3 on 2022-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesportcategory',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
