# Generated by Django 4.0.3 on 2022-03-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_articlesportcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesportcategory',
            name='category',
            field=models.CharField(choices=[('Football', 'Football'), ('Boxing', 'Boxing'), ('Formula 1', 'Formula 1')], max_length=9),
        ),
    ]
