# Generated by Django 4.0.3 on 2022-04-06 10:35

from django.db import migrations, models
import sports_app.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_articlesportcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesportcategory',
            name='category',
            field=models.CharField(max_length=30, unique=True, validators=[sports_app.common.validators.validate_letters_numbers_and_spaces_only]),
        ),
    ]
